site_name: Rex's Construct 2 plugins

pages:
    - Home: 'index.md'
    - Download tool: 'my-plugins-repository-v3.md'
    - Categories: 
        - System: 'system.index.md'
        - Data structure: 'datastructure.index.md'
        - Logic: 'logic.index.md'
        - String: 'string.index.md'
        - Date & time: 'date.index.md'
        - Timer: 'timer.index.md'
        - Text: 'text.index.md'
        - Movement behaviors: 'movement.index.md'
        - Input: 'input.index.md'
        - Board: 'board.index.md'
        - Backend:
            - 'Firebase': 'firebase.index.md'
            - 'Newgrounds.io': 'ngio.index.md'
    - List:
        - BBcode text: 'rex_bbcodetext.md'
        - JSON: 
            - Plugin: 'rex_hash.md'
            - Behavior: 'rex_bhash.md'
    - About: 'about.md'



extra_javascript:
    - js/mermaid.min.js
    - js/umlconvert.js
    
markdown_extensions:
    - pymdownx.superfences:
        custom_fences: [
           {name: mermaid, class: mermaid}
        ]
    - toc:
        permalink: True